CREATE TABLE IF NOT EXISTS favorites (
  id SERIAL PRIMARY KEY,
  imdb_id VARCHAR(20) UNIQUE NOT NULL,
  title VARCHAR(255) NOT NULL,
  year VARCHAR(10),
  poster TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);